import type { Locale } from './index';
type L = Exclude<Locale, 'en'>;

export const aboutCopy: Record<L, any> = {
  es: { kicker:'Acerca de',title:'Un desarrollador, un icono en la bandeja.',intro:[
    'Mouzi comenzó como muchas utilidades: con un desarrollador molesto y una carpeta de Descargas con cuatrocientos archivos. Quería una herramienta pequeña que organizara las nuevas descargas según mis propias reglas, funcionara desde la bandeja del sistema y nunca enviara datos a casa. Nada disponible cumplía las tres condiciones, así que la construí.',
    'Soy Krystian Welcel y desarrollo Mouzi en mi tiempo libre como proyecto independiente. Está escrito en Rust con Tauri, se publica para Windows y Linux y utiliza la licencia MIT. No hay una empresa detrás ni planes de añadir una suscripción. La aplicación es gratuita, el código es público y la hoja de ruta se guía por los issues de GitHub.'
  ],principles:'Principios',items:[['Solo local','Un organizador ve todo lo que descargas. Esos datos permanecen en tu equipo, sin excepciones.'],['Discreto','Mouzi debería pasar desapercibido un día después de instalarlo. Sin ventanas emergentes, ventas ni avisos que pidan atención.'],['Reversible','Los movimientos correctos quedan registrados en el Historial, desde donde Mouzi puede devolver un archivo si todavía existe en el destino.'],['Inspeccionable','El código y los workflows de publicación son públicos para que puedas comprobar cómo se construye la aplicación.']],stackTitle:'La tecnología, brevemente',stack:'Rust se encarga de vigilar archivos, ejecutar las reglas y guardar el historial en SQLite. Tauri proporciona la interfaz y permite mantener el instalador en unos pocos megabytes en lugar de incluir un navegador completo. La interfaz está traducida a 10 idiomas por colaboradores.',contactTitle:'Contacto',contact:'El mejor canal es GitHub: issues para errores y funciones, y avisos privados para problemas de seguridad. También puedes encontrarme en X, r/Mouzi o por correo electrónico.',impact:'Impacto del proyecto →',sponsor:'Patrocinar el proyecto →'},
  pl: { kicker:'O projekcie',title:'Jeden twórca, jedna ikona w zasobniku.',intro:[
    'Mouzi zaczęło się tak jak wiele małych narzędzi: od zirytowanego programisty i folderu Pobrane zawierającego czterysta plików. Chciałem niewielkiej aplikacji, która porządkuje nowe pliki według moich reguł, działa z zasobnika systemowego i nigdy nie wysyła danych na zewnątrz. Nic dostępnego nie spełniało wszystkich trzech warunków, więc zbudowałem Mouzi.',
    'Nazywam się Krystian Welcel i rozwijam Mouzi po godzinach jako niezależny projekt. Aplikacja jest napisana w Rust z użyciem Tauri, działa na Windowsie i Linuksie oraz jest udostępniana na licencji MIT. Nie stoi za nią firma i nie planuję dodawania subskrypcji. Program jest darmowy, kod publiczny, a kierunek rozwoju wynika ze zgłoszeń na GitHubie.'
  ],principles:'Zasady',items:[['Tylko lokalnie','Organizer plików widzi wszystko, co pobierasz. Te dane pozostają na Twoim komputerze.'],['Po cichu','Dzień po instalacji użytkownik powinien zapomnieć o Mouzi. Bez wyskakujących okien, sprzedaży i odznak walczących o uwagę.'],['Odwracalnie','Udane przeniesienia trafiają do Historii, z której Mouzi może przywrócić plik, jeśli nadal istnieje w zapisanym miejscu.'],['Przejrzyście','Kod źródłowy i proces wydawania są publiczne, więc możesz sprawdzić, jak powstaje aplikacja.']],stackTitle:'Technologia w skrócie',stack:'Rust odpowiada za obserwowanie plików, silnik reguł i historię SQLite. Tauri dostarcza warstwę interfejsu, dzięki czemu instalator ma kilka megabajtów zamiast zawierać całą przeglądarkę. Interfejs został przetłumaczony przez społeczność na 10 języków.',contactTitle:'Kontakt',contact:'Najlepszym miejscem jest GitHub: issues dla błędów i funkcji oraz prywatne zgłoszenia dla problemów bezpieczeństwa. Znajdziesz mnie również na X, r/Mouzi i pod adresem e-mail.',impact:'Wpływ projektu →',sponsor:'Wesprzyj projekt →'},
  de: { kicker:'Über Mouzi',title:'Ein Entwickler, ein Symbol im Infobereich.',intro:[
    'Mouzi begann wie viele kleine Werkzeuge: mit einem genervten Entwickler und einem Downloads-Ordner mit vierhundert Dateien. Ich wollte ein kleines Programm, das neue Downloads nach meinen Regeln sortiert, im Infobereich läuft und niemals Daten nach Hause sendet. Nichts erfüllte alle drei Anforderungen, also baute ich es selbst.',
    'Ich bin Krystian Welcel und entwickle Mouzi nach Feierabend als unabhängiges Projekt. Es ist in Rust mit Tauri geschrieben, erscheint für Windows und Linux und steht unter der MIT-Lizenz. Dahinter steht kein Unternehmen und es gibt keinen Plan für ein Abonnement. Die App ist kostenlos, der Quellcode öffentlich und die Roadmap wird durch GitHub-Issues bestimmt.'
  ],principles:'Grundsätze',items:[['Nur lokal','Ein Dateiorganisator sieht alle Downloads. Diese Daten bleiben ohne Ausnahme auf deinem Rechner.'],['Unaufdringlich','Einen Tag nach der Installation sollte Mouzi vergessen sein. Keine Pop-ups, Upsells oder Aufmerksamkeit fordernden Hinweise.'],['Umkehrbar','Erfolgreiche Verschiebungen werden im Verlauf gespeichert und können zurückgenommen werden, solange die Datei am Ziel vorhanden ist.'],['Nachvollziehbar','Quellcode und Release-Workflows sind öffentlich, sodass der Build-Prozess überprüft werden kann.']],stackTitle:'Der technische Aufbau',stack:'Rust übernimmt Dateiüberwachung, Regel-Engine und SQLite-Verlauf. Tauri stellt die Benutzeroberfläche bereit und hält den Installer bei wenigen Megabyte, statt einen kompletten Browser mitzuliefern. Mitwirkende haben die Oberfläche in 10 Sprachen übersetzt.',contactTitle:'Kontakt',contact:'Der beste Kanal ist GitHub: Issues für Fehler und Funktionen sowie private Advisories für Sicherheitsprobleme. Du findest mich auch auf X, r/Mouzi oder per E-Mail.',impact:'Projektwirkung →',sponsor:'Projekt unterstützen →'},
  fr: { kicker:'À propos',title:'Un développeur, une icône dans la zone de notification.',intro:[
    'Mouzi a commencé comme beaucoup de petits utilitaires : avec un développeur agacé et un dossier Téléchargements contenant quatre cents fichiers. Je voulais un outil léger qui trie les nouveaux fichiers selon mes propres règles, reste dans la zone de notification et ne transmette jamais de données. Rien ne réunissait ces trois qualités, alors je l’ai créé.',
    'Je m’appelle Krystian Welcel et je développe Mouzi pendant mon temps libre comme projet indépendant. Il est écrit en Rust avec Tauri, distribué pour Windows et Linux et publié sous licence MIT. Aucune entreprise ne se trouve derrière le projet et aucun abonnement n’est prévu. L’application est gratuite, le code public et la feuille de route guidée par les issues GitHub.'
  ],principles:'Principes',items:[['Entièrement local','Un organisateur voit tout ce que vous téléchargez. Ces données restent sur votre ordinateur.'],['Discret','Mouzi devrait se faire oublier dès le lendemain de son installation. Aucun pop-up, abonnement ou badge réclamant votre attention.'],['Réversible','Les déplacements réussis sont enregistrés dans l’Historique et peuvent être annulés si le fichier existe encore à destination.'],['Vérifiable','Le code source et les workflows de publication sont publics afin que chacun puisse examiner la construction de l’application.']],stackTitle:'La technologie, en bref',stack:'Rust gère la surveillance des fichiers, le moteur de règles et l’historique SQLite. Tauri fournit l’interface et permet de conserver un programme d’installation de quelques mégaoctets plutôt que d’intégrer un navigateur complet. L’interface est traduite en 10 langues par des contributeurs.',contactTitle:'Nous contacter',contact:'Le meilleur canal est GitHub : issues pour les bugs et fonctions, avis privés pour la sécurité. Vous pouvez également me joindre sur X, r/Mouzi ou par e-mail.',impact:'Impact du projet →',sponsor:'Soutenir le projet →'},
  it: { kicker:'Informazioni',title:'Uno sviluppatore, un’icona nell’area di notifica.',intro:[
    'Mouzi è nato come molti piccoli strumenti: da uno sviluppatore infastidito e una cartella Download con quattrocento file. Volevo un programma leggero che ordinasse i nuovi download secondo le mie regole, funzionasse dall’area di notifica e non inviasse mai dati all’esterno. Nessuna alternativa univa tutte e tre le caratteristiche, quindi l’ho costruito.',
    'Sono Krystian Welcel e sviluppo Mouzi nel tempo libero come progetto indipendente. È scritto in Rust con Tauri, distribuito per Windows e Linux e pubblicato con licenza MIT. Non c’è un’azienda dietro al progetto e non è previsto alcun abbonamento. L’app è gratuita, il codice pubblico e la roadmap è guidata dalle issue su GitHub.'
  ],principles:'Principi',items:[['Solo locale','Un organizzatore vede tutto ciò che scarichi. Questi dati restano sul tuo computer.'],['Discreto','Mouzi dovrebbe essere dimenticato il giorno dopo l’installazione. Niente popup, upsell o badge in cerca di attenzione.'],['Reversibile','Gli spostamenti riusciti vengono salvati nella Cronologia e possono essere annullati se il file esiste ancora nella destinazione.'],['Verificabile','Il codice sorgente e i workflow di rilascio sono pubblici, così puoi controllare come viene costruita l’applicazione.']],stackTitle:'La tecnologia, in breve',stack:'Rust gestisce il monitoraggio dei file, il motore delle regole e la cronologia SQLite. Tauri fornisce l’interfaccia e mantiene l’installer di pochi megabyte invece di includere un browser completo. L’interfaccia è tradotta in 10 lingue dai collaboratori.',contactTitle:'Contatti',contact:'Il canale migliore è GitHub: issue per bug e funzioni, segnalazioni private per la sicurezza. Puoi trovarmi anche su X, r/Mouzi o via e-mail.',impact:'Impatto del progetto →',sponsor:'Sostieni il progetto →'}
};
