import type { RoadmapStatus } from '../config/roadmap';

type Pair = [string, string];
type Copy = {
  features: { kicker:string; title:string; description:string; lead:string; cards:{title:string;body:string;alt:string}[]; demoKicker:string;demoTitle:string;demoBody:string;more:string;details:Pair[];docs:string };
  download: { title:string;description:string;lead:string;windowsGuide:string;linuxGuide:string;verifyTitle:string;verifyBody:string };
  faq: { kicker:string;title:string;description:string;missing:string;items:Pair[] };
  about: { title:string;description:string };
  roadmap: { kicker:string;title:string;description:string;lead:string;missing:string;sections:Record<RoadmapStatus,Pair>;items:Pair[] };
};

const commonImages = (titles: Pair[]) => titles.map(([title,body]) => ({ title, body, alt: title }));

const es: Copy = {
  features:{kicker:'Funciones',title:'Todo lo que hace Mouzi.',description:'Organización automática, reglas personalizadas, historial local y seguridad.',lead:'Una aplicación de bandeja con un solo trabajo: mantener organizadas las carpetas que elijas, a tu manera y sin enviar tus datos a ningún sitio.',cards:commonImages([['Organización automática','Vigila carpetas, aplica reglas y mueve archivos. En modo silencioso, manual o programado.'],['Reglas personalizadas','Extensiones, patrones de nombre, expresiones regulares, rutas dinámicas y prioridades.'],['Historial y deshacer con un clic','Revisa los movimientos recientes y restaura un archivo si una regla lo envía al lugar equivocado.'],['Privacidad y seguridad desde el diseño','Sin nube, cuenta ni telemetría. Las protecciones locales deciden cuándo es seguro mover un archivo.']]),demoKicker:'Míralo en acción',demoTitle:'Una carpeta de Descargas organizada en segundos.',demoBody:'Esta grabación muestra a Mouzi aplicando sus reglas y moviendo un grupo de archivos a sus carpetas de destino en Linux.',more:'Y el resto',details:[['Historial y deshacer','Los movimientos correctos se guardan localmente y pueden deshacerse desde Historial.'],['Detección segura de descargas','Periodos de espera, comprobación de bloqueos y exclusión de temporales.'],['Varias carpetas vigiladas','Cada carpeta tiene sus propias reglas y comportamiento.'],['Rutas dinámicas','{year} y {month} crean árboles de carpetas por fecha.'],['Exclusiones .mouziignore','Comodines, patrones de carpetas y comentarios en línea.'],['Limpiezas programadas','Hasta cuatro ejecuciones automáticas al día o modo manual.'],['Importación de Google Takeout','Descomprime y organiza archivos de Takeout en un paso.'],['10 idiomas','Inglés, polaco, alemán, francés, español, italiano y más.'],['Pequeña aplicación de bandeja','Creada con Rust y Tauri para trabajar discretamente.']],docs:'Leer la documentación'},
  download:{title:'Descargar Mouzi',description:'Mouzi para Windows y Linux: instalador, MSI, portable, AppImage, DEB y RPM.',lead:'Gratis y de código abierto con licencia MIT. Elige tu plataforma; ambas ofrecen las mismas funciones.',windowsGuide:'Guía de instalación para Windows',linuxGuide:'Guía de instalación para Linux',verifyTitle:'Verificar la descarga',verifyBody:'Los archivos públicos se compilan en GitHub Actions a partir de commits etiquetados y se publican oficialmente. La guía de seguridad explica cómo revisar una firma de Windows y calcular un hash SHA-256 local, además de los límites de esas comprobaciones.'},
  faq:{kicker:'Preguntas',title:'Preguntas frecuentes',description:'Respuestas sobre precio, privacidad, seguridad de las descargas, plataformas y desinstalación.',missing:'¿Falta algo? Pregunta en',items:[['¿Mouzi es realmente gratuito?','Sí. Es código abierto con licencia MIT. No hay plan de pago, prueba ni funciones bloqueadas.'],['¿Mouzi sube mis archivos?','No. No tiene servidor. Las reglas y el historial funcionan localmente; solo la comprobación opcional de versiones consulta GitHub.'],['¿Y si una regla mueve un archivo necesario?','Abre Historial y pulsa deshacer. Si aún existe en el destino, Mouzi lo devuelve. Luego corrige la regla o .mouziignore.'],['¿Moverá un archivo aún en descarga?','Un periodo de gracia, la exclusión de .crdownload y .part, los archivos vacíos y los bloqueos reducen el riesgo. Las limpiezas manuales y programadas son inmediatas.'],['¿Por qué avisa SmartScreen?','La versión 0.1.5 no está firmada mientras se prepara la firma de producción con SignPath Foundation. Descarga solo desde mouzi.cc o GitHub oficial.'],['¿Qué plataformas se admiten?','Windows 10/11 x64 y Linux x86_64 en AppImage, DEB y RPM. macOS sigue siendo experimental.'],['¿Puedo vigilar otras carpetas?','Sí, varias a la vez y cada una con sus propias reglas.'],['¿Funciona con OneDrive o Google Drive?','Normalmente sí, porque usa operaciones normales del sistema de archivos. Prueba primero con archivos no importantes.'],['¿Cómo lo elimino por completo?','Desinstala y borra %APPDATA%\\Mouzi en Windows o ~/.config/mouzi en Linux. Para la versión portátil, borra el archivo.'],['¿Cómo puedo colaborar?','Código, traducciones, documentación e informes son bienvenidos en el repositorio y sus Issues.']]},
  about:{title:'Acerca de Mouzi',description:'La historia, los principios y la tecnología del proyecto Mouzi.'},
  roadmap:{kicker:'Dirección',title:'Hoja de ruta',description:'Trabajo actual, próximas funciones y entregas de Mouzi.',lead:'Qué está en desarrollo, qué viene después y qué ya se publicó. Salvo «Publicado», son intenciones y no compromisos.',missing:'¿Quieres algo que no aparece aquí? Abre una solicitud en',sections:{now:['Ahora','En desarrollo activo.'],next:['Después','Previsto para próximas versiones.'],later:['Más adelante','En la lista, todavía sin fecha.'],shipped:['Publicado','Ya está en manos de los usuarios.']},items:[['Selector de carpeta para destinos','Un selector junto al destino; conserva rutas relativas dentro de la carpeta vigilada y admite rutas absolutas fuera.'],['Ayudas y accesibilidad','Ayudas traducidas y nombres accesibles para botones con solo icono.'],['Activar reglas rápidamente','Cambia una regla sin abrir el editor. Integrado para v0.1.6, aún no publicado.'],['Búsqueda y filtros del historial','Filtra por nombre, regla, tipo y fecha.'],['Corrección del icono AppImage','Corrige el enlace absoluto roto que impide instalar con AppManager.'],['Versiones Windows firmadas','Firma de producción mediante SignPath Foundation; certificado en emisión.'],['Vigilancia recursiva','Vigilancia profunda opcional protegida contra destinos y bucles.'],['Condiciones de tamaño y fecha','Reglas por tamaño y modificación; la creación necesita revisión multiplataforma.'],['Ejecutables sin extensión','Detectar y gestionar ejecutables sin extensión.'],['Limpieza automática de capturas','Enviar opcionalmente a la Papelera capturas más antiguas que el periodo elegido.'],['Paquetes Linux','AppImage, DEB y RPM para x86_64.'],['Limpiezas programadas','Organización automática hasta cuatro veces al día.']]}
};

const pl: Copy = {
  features:{kicker:'Funkcje',title:'Wszystko, co potrafi Mouzi.',description:'Automatyczna organizacja, własne reguły, lokalna historia i bezpieczeństwo.',lead:'Aplikacja zasobnika z jednym zadaniem: utrzymywać wybrane foldery w porządku, na Twoich zasadach i bez wysyłania danych gdziekolwiek.',cards:commonImages([['Automatyczna organizacja','Obserwuje foldery, stosuje reguły i przenosi pliki. Tryb cichy, ręczny lub harmonogram.'],['Własne reguły','Rozszerzenia, wzorce nazw, regex, dynamiczne ścieżki i priorytety.'],['Historia i cofanie jednym kliknięciem','Przejrzyj przeniesienia i przywróć plik wysłany w złe miejsce.'],['Prywatność i bezpieczeństwo od podstaw','Bez chmury, konta i telemetrii. Lokalne zabezpieczenia określają, kiedy można przenieść plik.']]),demoKicker:'Zobacz działanie',demoTitle:'Folder Pobrane uporządkowany w kilka sekund.',demoBody:'Nagranie pokazuje, jak Mouzi stosuje reguły i przenosi różne pliki do folderów docelowych w Linuksie.',more:'Pozostałe możliwości',details:[['Historia i cofanie','Udane przeniesienia są zapisane lokalnie i można je cofnąć.'],['Bezpieczne wykrywanie pobrań','Okres ochronny, kontrola blokady i pomijanie plików tymczasowych.'],['Wiele obserwowanych folderów','Każdy folder ma własne reguły i zachowanie.'],['Dynamiczne ścieżki','{year} i {month} tworzą drzewa folderów według dat.'],['Wykluczenia .mouziignore','Symbole wieloznaczne, wzorce folderów i komentarze.'],['Harmonogram','Do czterech automatycznych uruchomień dziennie lub tryb ręczny.'],['Import Google Takeout','Rozpakowanie i posortowanie archiwum w jednym kroku.'],['10 języków','Angielski, polski, niemiecki, francuski, hiszpański, włoski i inne.'],['Mała aplikacja zasobnika','Rust i Tauri pozwalają jej dyskretnie działać w tle.']],docs:'Przeczytaj dokumentację'},
  download:{title:'Pobierz Mouzi',description:'Mouzi dla Windows i Linuksa: instalator, MSI, portable, AppImage, DEB i RPM.',lead:'Darmowe i otwarte oprogramowanie na licencji MIT. Wybierz platformę; obie oferują te same funkcje.',windowsGuide:'Instrukcja instalacji w Windows',linuxGuide:'Instrukcja instalacji w Linuksie',verifyTitle:'Weryfikacja pobranego pliku',verifyBody:'Publiczne pliki są budowane przez GitHub Actions z oznaczonych commitów i publikowane oficjalnie. Przewodnik bezpieczeństwa wyjaśnia sprawdzanie podpisu Windows i obliczanie lokalnego SHA-256 wraz z ograniczeniami tych metod.'},
  faq:{kicker:'Pytania',title:'Najczęściej zadawane pytania',description:'Odpowiedzi o cenie, prywatności, bezpieczeństwie pobrań, platformach i odinstalowaniu.',missing:'Brakuje odpowiedzi? Zapytaj na',items:[['Czy Mouzi naprawdę jest darmowe?','Tak. To otwarte oprogramowanie na licencji MIT, bez płatnego planu, okresu próbnego i blokad funkcji.'],['Czy Mouzi gdzieś wysyła pliki?','Nie. Nie ma serwera. Reguły i historia działają lokalnie; tylko opcjonalna kontrola wersji łączy się z GitHubem.'],['Co jeśli reguła przeniesie potrzebny plik?','Otwórz Historię i cofnij wpis. Jeśli plik nadal jest w zapisanym celu, Mouzi go przywróci. Potem popraw regułę lub .mouziignore.'],['Czy przeniesie nieukończone pobieranie?','Ryzyko ograniczają okres ochronny, pomijanie .crdownload i .part, pustych plików oraz kontrola blokady. Tryb ręczny i harmonogram działają natychmiast.'],['Dlaczego SmartScreen ostrzega?','Wersja 0.1.5 jest niepodpisana podczas przygotowania podpisu SignPath Foundation. Pobieraj tylko z mouzi.cc lub oficjalnego GitHuba.'],['Jakie platformy są obsługiwane?','Windows 10/11 x64 i Linux x86_64 jako AppImage, DEB i RPM. macOS jest eksperymentalny.'],['Czy można obserwować inne foldery?','Tak, wiele jednocześnie i każdy z własnymi regułami.'],['Czy działa z OneDrive lub Google Drive?','Zwykle tak, bo używa zwykłych operacji systemu plików. Najpierw testuj na nieistotnych plikach.'],['Jak całkowicie usunąć Mouzi?','Odinstaluj i usuń %APPDATA%\\Mouzi w Windows albo ~/.config/mouzi w Linuksie. Wersję portable wystarczy skasować.'],['Jak mogę pomóc?','Kod, tłumaczenia, dokumentacja i zgłoszenia błędów są mile widziane w repozytorium i Issues.']]},
  about:{title:'O Mouzi',description:'Historia, zasady i technologia projektu Mouzi.'},
  roadmap:{kicker:'Kierunek',title:'Plan rozwoju',description:'Bieżące prace, następne funkcje i wydane elementy Mouzi.',lead:'Co jest w trakcie, co planujemy i co już trafiło do użytkowników. Poza „Wydane” są to zamiary, nie obietnice.',missing:'Brakuje ważnej funkcji? Otwórz zgłoszenie na',sections:{now:['Teraz','W aktywnym rozwoju.'],next:['Następne','Planowane w kolejnych wydaniach.'],later:['Później','Na liście, bez terminu.'],shipped:['Wydane','Już dostępne dla użytkowników.']},items:[['Wybór folderu docelowego','Przycisk obok pola celu; zachowuje ścieżki względne wewnątrz obserwowanego folderu i pozwala wybrać bezwzględne poza nim.'],['Podpowiedzi i dostępność','Przetłumaczone podpowiedzi i dostępne nazwy przycisków z samą ikoną.'],['Szybkie włączanie reguł','Zmiana stanu bez edytora. Scalono dla v0.1.6, jeszcze niewydane.'],['Wyszukiwanie i filtry historii','Filtrowanie według nazwy, reguły, typu i daty.'],['Naprawa ikony AppImage','Usunięcie błędnego dowiązania, które psuje instalację w AppManagerze.'],['Podpisane wydania Windows','Podpis produkcyjny przez SignPath Foundation; trwa wydawanie certyfikatu.'],['Rekurencyjne obserwowanie','Opcjonalne głębokie obserwowanie z ochroną przed celami i pętlami.'],['Warunki rozmiaru i daty','Reguły według rozmiaru i modyfikacji; data utworzenia wymaga analizy.'],['Programy bez rozszerzenia','Wykrywanie i obsługa plików wykonywalnych bez rozszerzeń.'],['Sprzątanie zrzutów ekranu','Opcjonalne przenoszenie starszych zrzutów do Kosza po wybranym czasie.'],['Pakiety Linux','AppImage, DEB i RPM dla x86_64.'],['Harmonogram','Automatyczna organizacja do czterech razy dziennie.']]}
};

const de: Copy = {
  features:{kicker:'Funktionen',title:'Alles, was Mouzi kann.',description:'Automatische Organisation, eigene Regeln, lokaler Verlauf und Sicherheit.',lead:'Eine Tray-App mit einer Aufgabe: ausgewählte Ordner nach deinen Regeln ordnen, ohne Daten irgendwohin zu senden.',cards:commonImages([['Automatische Organisation','Ordner überwachen, Regeln anwenden und Dateien verschieben: leise, manuell oder geplant.'],['Eigene Regeln','Erweiterungen, Namensmuster, Regex, dynamische Pfade und Prioritäten.'],['Verlauf und Rückgängig','Letzte Verschiebungen prüfen und falsch einsortierte Dateien wiederherstellen.'],['Datenschutz und Sicherheit','Keine Cloud, kein Konto, keine Telemetrie. Lokale Schutzmechanismen prüfen Dateien.']]),demoKicker:'In Aktion',demoTitle:'Ein Download-Ordner, in Sekunden sortiert.',demoBody:'Die Aufnahme zeigt, wie Mouzi unter Linux Regeln anwendet und verschiedene Dateien in Zielordner verschiebt.',more:'Weitere Funktionen',details:[['Verlauf und Rückgängig','Verschiebungen werden lokal gespeichert und lassen sich rückgängig machen.'],['Sichere Download-Erkennung','Wartezeit, Sperrprüfung und Ausschluss temporärer Dateien.'],['Mehrere Ordner','Jeder überwachte Ordner hat eigene Regeln.'],['Dynamische Pfade','{year} und {month} erzeugen datierte Strukturen.'],['.mouziignore','Wildcards, Ordnermuster und Inline-Kommentare.'],['Geplante Läufe','Bis zu vier Läufe täglich oder vollständig manuell.'],['Google Takeout','Archive in einem Schritt entpacken und sortieren.'],['10 Sprachen','Deutsch, Englisch, Polnisch, Französisch, Spanisch, Italienisch und mehr.'],['Kleine Tray-App','Mit Rust und Tauri für diskreten Hintergrundbetrieb.']],docs:'Dokumentation lesen'},
  download:{title:'Mouzi herunterladen',description:'Mouzi für Windows und Linux: Installer, MSI, portable, AppImage, DEB und RPM.',lead:'Kostenlos und quelloffen unter MIT. Beide Plattformen bieten dieselben Funktionen.',windowsGuide:'Windows-Installationsanleitung',linuxGuide:'Linux-Installationsanleitung',verifyTitle:'Download überprüfen',verifyBody:'Öffentliche Dateien werden in GitHub Actions aus markierten Commits gebaut und offiziell veröffentlicht. Der Sicherheitsleitfaden erklärt Windows-Signaturen, lokale SHA-256-Prüfsummen und deren Grenzen.'},
  faq:{kicker:'Fragen',title:'Häufig gestellte Fragen',description:'Antworten zu Preis, Datenschutz, Download-Sicherheit, Plattformen und Entfernung.',missing:'Noch eine Frage? Stelle sie auf',items:[['Ist Mouzi wirklich kostenlos?','Ja. Quelloffen unter MIT, ohne Bezahlstufe, Testphase oder gesperrte Funktionen.'],['Werden Dateien hochgeladen?','Nein. Es gibt keinen Server. Regeln und Verlauf bleiben lokal; nur die optionale Versionsprüfung fragt GitHub ab.'],['Was bei einer falschen Verschiebung?','Im Verlauf Rückgängig wählen. Liegt die Datei noch am Ziel, bringt Mouzi sie zurück. Danach Regel oder .mouziignore anpassen.'],['Werden laufende Downloads verschoben?','Wartezeit, .crdownload/.part-Ausschluss, Null-Byte- und Sperrprüfung verringern das Risiko. Manuelle und geplante Läufe starten sofort.'],['Warum warnt SmartScreen?','0.1.5 ist noch unsigniert, während die SignPath-Produktionssignatur vorbereitet wird. Nur von mouzi.cc oder GitHub laden.'],['Welche Systeme werden unterstützt?','Windows 10/11 x64 und Linux x86_64 als AppImage, DEB und RPM. macOS ist experimentell.'],['Andere Ordner überwachen?','Ja, mehrere gleichzeitig mit jeweils eigenen Regeln.'],['OneDrive oder Google Drive?','Meist ja, da normale Dateisystemoperationen verwendet werden. Zuerst mit unwichtigen Dateien testen.'],['Wie vollständig entfernen?','Deinstallieren und %APPDATA%\\Mouzi beziehungsweise ~/.config/mouzi löschen. Portable: Datei löschen.'],['Wie kann ich helfen?','Code, Übersetzungen, Dokumentation und Fehlerberichte sind im Repository willkommen.']]},
  about:{title:'Über Mouzi',description:'Geschichte, Prinzipien und Technik des Mouzi-Projekts.'},
  roadmap:{kicker:'Richtung',title:'Roadmap',description:'Aktuelle Arbeit, nächste Funktionen und veröffentlichte Neuerungen.',lead:'Was entsteht, was folgt und was bereits veröffentlicht wurde. Außer „Veröffentlicht“ sind dies Absichten, keine Zusagen.',missing:'Fehlt etwas? Anfrage öffnen auf',sections:{now:['Jetzt','In aktiver Entwicklung.'],next:['Als Nächstes','Für kommende Versionen geplant.'],later:['Später','Auf der Liste, noch ohne Termin.'],shipped:['Veröffentlicht','Bereits verfügbar.']},items:[['Ordnerauswahl für Ziele','Auswahl am Zielfeld; relative Pfade innen bleiben erhalten, absolute Pfade außen sind möglich.'],['Tooltips und Barrierefreiheit','Übersetzte Hinweise und zugängliche Namen für Symbolschaltflächen.'],['Regeln schnell schalten','Ohne Editor aktivieren. Für v0.1.6 integriert, noch nicht veröffentlicht.'],['Verlaufssuche und Filter','Nach Name, Regel, Typ und Datum filtern.'],['AppImage-Symbol korrigieren','Defekten absoluten Link beheben, der AppManager verhindert.'],['Signierte Windows-Versionen','Produktionssignatur über SignPath; Zertifikat wird ausgestellt.'],['Rekursive Überwachung','Optionale Tiefe mit Schutz vor Zielordnern und Schleifen.'],['Größe und Datum','Regeln nach Größe und Änderung; Erstellungsdatum braucht Prüfung.'],['Programme ohne Erweiterung','Ausführbare Dateien ohne Erweiterung erkennen.'],['Screenshot-Bereinigung','Alte Screenshots nach gewählter Frist in den Papierkorb verschieben.'],['Linux-Pakete','AppImage, DEB und RPM für x86_64.'],['Geplante Läufe','Automatische Organisation bis zu viermal täglich.']]}
};

const fr: Copy = {
  features:{kicker:'Fonctionnalités',title:'Tout ce que fait Mouzi.',description:'Organisation automatique, règles personnalisées, historique local et sécurité.',lead:'Une application de zone de notification avec une mission : ranger vos dossiers selon vos règles, sans envoyer vos données ailleurs.',cards:commonImages([['Organisation automatique','Surveille les dossiers, applique les règles et déplace les fichiers, en silence, manuellement ou selon un horaire.'],['Règles personnalisées','Extensions, motifs de nom, expressions régulières, chemins dynamiques et priorités.'],['Historique et annulation','Consultez les déplacements et restaurez un fichier envoyé au mauvais endroit.'],['Confidentialité et sécurité','Sans cloud, compte ni télémétrie. Des protections locales vérifient les fichiers.']]),demoKicker:'Voir Mouzi agir',demoTitle:'Un dossier Téléchargements rangé en quelques secondes.',demoBody:'La vidéo montre Mouzi appliquant ses règles et déplaçant différents fichiers sous Linux.',more:'Et aussi',details:[['Historique et annulation','Les déplacements sont enregistrés localement et peuvent être annulés.'],['Téléchargements protégés','Délai, contrôle des verrous et exclusion des fichiers temporaires.'],['Plusieurs dossiers','Chaque dossier surveillé possède ses règles.'],['Chemins dynamiques','{year} et {month} créent une arborescence datée.'],['.mouziignore','Jokers, motifs de dossiers et commentaires.'],['Rangements planifiés','Jusqu’à quatre passages par jour ou mode manuel.'],['Google Takeout','Décompresse et trie les archives en une étape.'],['10 langues','Français, anglais, polonais, allemand, espagnol, italien et plus.'],['Petite application','Rust et Tauri pour un fonctionnement discret.']],docs:'Lire la documentation'},
  download:{title:'Télécharger Mouzi',description:'Mouzi pour Windows et Linux : installateur, MSI, portable, AppImage, DEB et RPM.',lead:'Gratuit et open source sous MIT. Les deux plateformes proposent les mêmes fonctions.',windowsGuide:'Guide d’installation Windows',linuxGuide:'Guide d’installation Linux',verifyTitle:'Vérifier le téléchargement',verifyBody:'Les fichiers publics sont compilés par GitHub Actions depuis les commits balisés et publiés officiellement. Le guide de sécurité explique signatures Windows, SHA-256 local et limites de ces contrôles.'},
  faq:{kicker:'Questions',title:'Questions fréquentes',description:'Réponses sur le prix, la confidentialité, la sécurité, les plateformes et la désinstallation.',missing:'Une question manque ? Posez-la sur',items:[['Mouzi est-il vraiment gratuit ?','Oui. Open source sous MIT, sans abonnement, essai ni fonction bloquée.'],['Mes fichiers sont-ils envoyés ?','Non. Aucun serveur. Règles et historique restent locaux ; seule la recherche facultative de versions contacte GitHub.'],['Une règle a mal classé un fichier ?','Utilisez Annuler dans l’Historique. Si le fichier existe encore au nouvel emplacement, Mouzi le remet. Corrigez ensuite la règle ou .mouziignore.'],['Un téléchargement en cours sera-t-il déplacé ?','Délai, exclusion de .crdownload/.part, fichiers vides et verrous réduisent le risque. Les passages manuels et planifiés sont immédiats.'],['Pourquoi SmartScreen avertit-il ?','La 0.1.5 n’est pas signée pendant la préparation SignPath. Téléchargez uniquement depuis mouzi.cc ou GitHub officiel.'],['Quelles plateformes ?','Windows 10/11 x64 et Linux x86_64 en AppImage, DEB et RPM. macOS reste expérimental.'],['D’autres dossiers ?','Oui, plusieurs à la fois avec leurs propres règles.'],['OneDrive ou Google Drive ?','Généralement oui, grâce aux opérations normales du système de fichiers. Testez avec des fichiers sans importance.'],['Comment tout supprimer ?','Désinstallez puis supprimez %APPDATA%\\Mouzi ou ~/.config/mouzi. Portable : supprimez le fichier.'],['Comment contribuer ?','Code, traductions, documentation et rapports sont bienvenus sur le dépôt.']]},
  about:{title:'À propos de Mouzi',description:'Histoire, principes et technologie du projet Mouzi.'},
  roadmap:{kicker:'Direction',title:'Feuille de route',description:'Travail actuel, prochaines fonctions et éléments publiés.',lead:'Ce qui est en cours, ce qui suit et ce qui est déjà livré. Sauf « Livré », ce sont des intentions, pas des promesses.',missing:'Une fonction manque ? Demandez-la sur',sections:{now:['Maintenant','En développement actif.'],next:['Ensuite','Prévu pour les prochaines versions.'],later:['Plus tard','Dans la liste, sans date.'],shipped:['Livré','Déjà disponible.']},items:[['Sélecteur de destination','Conserve les chemins relatifs dans le dossier et autorise les chemins absolus ailleurs.'],['Infobulles et accessibilité','Infobulles traduites et noms accessibles pour les boutons à icône.'],['Activation rapide','Changez une règle sans éditeur. Fusionné pour v0.1.6, pas encore publié.'],['Recherche dans l’historique','Filtres par nom, règle, type et date.'],['Icône AppImage','Corriger le lien absolu qui bloque AppManager.'],['Versions Windows signées','Signature SignPath ; certificat en cours d’émission.'],['Surveillance récursive','Profondeur facultative protégée contre destinations et boucles.'],['Taille et date','Conditions sur taille et modification ; création à étudier.'],['Exécutables sans extension','Détecter les programmes sans extension.'],['Nettoyage des captures','Envoyer les anciennes captures à la Corbeille après la durée choisie.'],['Paquets Linux','AppImage, DEB et RPM x86_64.'],['Passages planifiés','Organisation jusqu’à quatre fois par jour.']]}
};

const it: Copy = {
  features:{kicker:'Funzionalità',title:'Tutto ciò che fa Mouzi.',description:'Organizzazione automatica, regole personalizzate, cronologia locale e sicurezza.',lead:'Un’app nella barra con un compito: ordinare le cartelle scelte secondo le tue regole, senza inviare dati altrove.',cards:commonImages([['Organizzazione automatica','Controlla cartelle, applica regole e sposta file in modo silenzioso, manuale o programmato.'],['Regole personalizzate','Estensioni, nomi, regex, percorsi dinamici e priorità.'],['Cronologia e annullamento','Controlla gli spostamenti e ripristina un file finito nel posto sbagliato.'],['Privacy e sicurezza','Niente cloud, account o telemetria. Le protezioni locali controllano i file.']]),demoKicker:'Guardalo in azione',demoTitle:'Una cartella Download ordinata in pochi secondi.',demoBody:'Il video mostra Mouzi che applica le regole e sposta diversi file su Linux.',more:'E il resto',details:[['Cronologia e annullamento','Gli spostamenti sono salvati localmente e annullabili.'],['Download protetti','Attesa, controllo blocchi ed esclusione dei temporanei.'],['Più cartelle','Ogni cartella controllata ha regole proprie.'],['Percorsi dinamici','{year} e {month} creano strutture per data.'],['.mouziignore','Caratteri jolly, modelli e commenti.'],['Pulizie programmate','Fino a quattro esecuzioni al giorno o modalità manuale.'],['Google Takeout','Estrae e ordina archivi in un passaggio.'],['10 lingue','Italiano, inglese, polacco, tedesco, francese, spagnolo e altre.'],['Piccola app','Rust e Tauri per lavorare discretamente.']],docs:'Leggi la documentazione'},
  download:{title:'Scarica Mouzi',description:'Mouzi per Windows e Linux: installer, MSI, portable, AppImage, DEB e RPM.',lead:'Gratuito e open source con licenza MIT. Le piattaforme hanno le stesse funzioni.',windowsGuide:'Guida Windows',linuxGuide:'Guida Linux',verifyTitle:'Verifica del download',verifyBody:'I file pubblici sono compilati da GitHub Actions dai commit con tag e pubblicati ufficialmente. La guida sicurezza spiega firme Windows, SHA-256 locale e limiti dei controlli.'},
  faq:{kicker:'Domande',title:'Domande frequenti',description:'Risposte su prezzo, privacy, sicurezza, piattaforme e rimozione.',missing:'Manca una domanda? Chiedi su',items:[['Mouzi è davvero gratuito?','Sì. Open source MIT, senza piano a pagamento, prova o funzioni bloccate.'],['Invia i miei file?','No. Nessun server. Regole e cronologia restano locali; solo il controllo facoltativo delle versioni contatta GitHub.'],['Una regola ha spostato male un file?','Usa Annulla nella Cronologia. Se il file esiste ancora, Mouzi lo riporta. Poi correggi regola o .mouziignore.'],['Sposta download in corso?','Attesa, esclusione .crdownload/.part, file vuoti e blocchi riducono il rischio. Pulizie manuali e programmate sono immediate.'],['Perché SmartScreen avvisa?','La 0.1.5 non è firmata durante la preparazione SignPath. Scarica solo da mouzi.cc o GitHub ufficiale.'],['Quali piattaforme?','Windows 10/11 x64 e Linux x86_64 in AppImage, DEB e RPM. macOS è sperimentale.'],['Altre cartelle?','Sì, più cartelle con regole proprie.'],['OneDrive o Google Drive?','In genere sì, usando normali operazioni file. Prova prima con file non importanti.'],['Come rimuoverlo del tutto?','Disinstalla e cancella %APPDATA%\\Mouzi o ~/.config/mouzi. Portable: elimina il file.'],['Come contribuire?','Codice, traduzioni, documentazione e segnalazioni sono benvenuti.']]},
  about:{title:'Informazioni su Mouzi',description:'Storia, principi e tecnologia del progetto Mouzi.'},
  roadmap:{kicker:'Direzione',title:'Roadmap',description:'Lavori attuali, prossime funzioni e novità pubblicate.',lead:'Cosa è in corso, cosa seguirà e cosa è già rilasciato. Tranne “Rilasciato”, sono intenzioni, non promesse.',missing:'Manca una funzione? Richiedila su',sections:{now:['Ora','In sviluppo attivo.'],next:['Prossimo','Previsto per le prossime versioni.'],later:['Più avanti','In elenco, senza data.'],shipped:['Rilasciato','Già disponibile.']},items:[['Selettore destinazione','Mantiene percorsi relativi nella cartella e consente assoluti fuori.'],['Suggerimenti e accessibilità','Suggerimenti tradotti e nomi accessibili per pulsanti a icona.'],['Attivazione rapida','Cambia regola senza editor. Integrato per v0.1.6, non pubblicato.'],['Ricerca cronologia','Filtri per nome, regola, tipo e data.'],['Icona AppImage','Corregge il collegamento che blocca AppManager.'],['Versioni Windows firmate','Firma SignPath; certificato in emissione.'],['Controllo ricorsivo','Profondità opzionale protetta da destinazioni e cicli.'],['Dimensione e data','Condizioni per dimensione e modifica; creazione da valutare.'],['Eseguibili senza estensione','Rileva programmi senza estensione.'],['Pulizia screenshot','Sposta vecchie catture nel Cestino dopo il periodo scelto.'],['Pacchetti Linux','AppImage, DEB e RPM x86_64.'],['Pulizie programmate','Organizzazione fino a quattro volte al giorno.']]}
};

const release016Copy = {
  es: {
    smartScreen: 'La versión 0.1.6 no está firmada con Authenticode mientras se prepara la firma de producción con SignPath Foundation. Descarga solo desde mouzi.cc o GitHub oficial.',
    quickToggle: 'Activa o desactiva una regla sin abrir el editor.',
    extensionless: 'Detecta por su contenido archivos reconocibles sin extensión y aplica las reglas existentes.',
    scheduled: ['Organización programada','Hasta cuatro ejecuciones automáticas al día o modo manual.'] as Pair,
    roadmap: ['Organización más segura, lotes selectivos y actualizaciones automáticas','Añade paquetes de actualización firmados, lotes de archivos seleccionados, acciones en la Papelera, normalización de extensiones, avisos personalizados, confirmación del historial y el término Organizar.'] as Pair,
  },
  pl: {
    smartScreen: 'Wersja 0.1.6 nie jest podpisana Authenticode podczas przygotowania podpisu SignPath Foundation. Pobieraj tylko z mouzi.cc lub oficjalnego GitHuba.',
    quickToggle: 'Włączaj i wyłączaj regułę bez otwierania edytora.',
    extensionless: 'Rozpoznaje po zawartości pliki bez rozszerzeń i stosuje istniejące reguły.',
    scheduled: ['Organizacja według harmonogramu','Do czterech automatycznych uruchomień dziennie lub tryb ręczny.'] as Pair,
    roadmap: ['Bezpieczniejsza organizacja, wybrane partie i automatyczne aktualizacje','Dodaje podpisane pakiety aktualizacji, partie wybranych plików, działania przez Kosz, normalizację rozszerzeń, własne powiadomienia, potwierdzenie historii i nazewnictwo Organizuj.'] as Pair,
  },
  de: {
    smartScreen: '0.1.6 ist noch nicht mit Authenticode signiert, während die SignPath-Produktionssignatur vorbereitet wird. Nur von mouzi.cc oder GitHub laden.',
    quickToggle: 'Regeln ohne Öffnen des Editors ein- oder ausschalten.',
    extensionless: 'Erkennt bekannte Dateien ohne Endung am Inhalt und wendet vorhandene Regeln an.',
    scheduled: ['Geplante Organisation','Bis zu vier automatische Läufe täglich oder vollständig manuell.'] as Pair,
    roadmap: ['Sicherere Organisation, ausgewählte Stapel und automatische Updates','Bietet signierte Updatepakete, ausgewählte Dateistapel, Papierkorb-Aktionen, Endungsnormalisierung, eigene Benachrichtigungen, Verlaufsbestätigung und klare Organisieren-Bezeichnungen.'] as Pair,
  },
  fr: {
    smartScreen: 'La 0.1.6 n’est pas signée avec Authenticode pendant la préparation SignPath. Téléchargez uniquement depuis mouzi.cc ou GitHub officiel.',
    quickToggle: 'Activez ou désactivez une règle sans ouvrir l’éditeur.',
    extensionless: 'Reconnaît le contenu des fichiers sans extension et applique les règles existantes.',
    scheduled: ['Organisation planifiée','Jusqu’à quatre passages automatiques par jour ou mode manuel.'] as Pair,
    roadmap: ['Organisation plus sûre, lots sélectionnés et mises à jour automatiques','Ajoute des paquets de mise à jour signés, des lots sélectionnés, la Corbeille, la normalisation des extensions, les notifications personnalisées, la confirmation de l’historique et le terme Organiser.'] as Pair,
  },
  it: {
    smartScreen: 'La 0.1.6 non è firmata con Authenticode durante la preparazione SignPath. Scarica solo da mouzi.cc o GitHub ufficiale.',
    quickToggle: 'Attiva o disattiva una regola senza aprire l’editor.',
    extensionless: 'Riconosce dal contenuto i file senza estensione e applica le regole esistenti.',
    scheduled: ['Organizzazione programmata','Fino a quattro esecuzioni automatiche al giorno o modalità manuale.'] as Pair,
    roadmap: ['Organizzazione più sicura, gruppi selezionati e aggiornamenti automatici','Aggiunge pacchetti di aggiornamento firmati, gruppi di file selezionati, azioni nel Cestino, normalizzazione estensioni, notifiche personalizzate, conferma della cronologia e la dicitura Organizza.'] as Pair,
  },
};

const localizedPages = { es, pl, de, fr, it };
for (const lang of Object.keys(localizedPages) as Array<keyof typeof localizedPages>) {
  const page = localizedPages[lang];
  const release = release016Copy[lang];
  page.faq.items[4][1] = release.smartScreen;
  page.roadmap.items[2][1] = release.quickToggle;
  page.roadmap.items[8][1] = release.extensionless;
  page.roadmap.items.push(release.roadmap);
  page.features.details[5] = release.scheduled;
}

export const corePageCopy = localizedPages satisfies Record<'es'|'pl'|'de'|'fr'|'it', Copy>;
