export const locales = ['en', 'es', 'pl', 'de', 'fr', 'it'] as const;
export const translatedLocales = locales.filter((locale) => locale !== 'en');
export type Locale = (typeof locales)[number];

export const localeNames: Record<Locale, string> = {
  en: 'English', es: 'Español', pl: 'Polski', de: 'Deutsch', fr: 'Français', it: 'Italiano',
};

export function localeFromPath(pathname: string): Locale {
  const candidate = pathname.split('/').filter(Boolean)[0]?.replace(/\.html$/, '') as Locale | undefined;
  return candidate && locales.includes(candidate) ? candidate : 'en';
}

export function stripLocale(pathname: string): string {
  const locale = localeFromPath(pathname);
  const cleanPath = pathname.replace(/\.html$/, '');
  if (locale === 'en') return cleanPath || '/';
  const stripped = cleanPath.replace(new RegExp(`^/${locale}(?=/|$)`), '');
  return stripped || '/';
}

export function localizedPath(pathname: string, locale: Locale): string {
  const path = stripLocale(pathname);
  return locale === 'en' ? path : `/${locale}${path === '/' ? '' : path}`;
}

export const common = {
  en: { features: 'Features', docs: 'Docs', roadmap: 'Roadmap', blog: 'Blog', about: 'About', support: 'Support', download: 'Download', menu: 'Menu', open: 'Open menu', close: 'Close menu', skip: 'Skip to content', language: 'Language' },
  es: { features: 'Funciones', docs: 'Documentación', roadmap: 'Hoja de ruta', blog: 'Blog', about: 'Acerca de', support: 'Apoyar', download: 'Descargar', menu: 'Menú', open: 'Abrir menú', close: 'Cerrar menú', skip: 'Saltar al contenido', language: 'Idioma' },
  pl: { features: 'Funkcje', docs: 'Dokumentacja', roadmap: 'Plan rozwoju', blog: 'Blog', about: 'O projekcie', support: 'Wesprzyj', download: 'Pobierz', menu: 'Menu', open: 'Otwórz menu', close: 'Zamknij menu', skip: 'Przejdź do treści', language: 'Język' },
  de: { features: 'Funktionen', docs: 'Dokumentation', roadmap: 'Roadmap', blog: 'Blog', about: 'Über Mouzi', support: 'Unterstützen', download: 'Herunterladen', menu: 'Menü', open: 'Menü öffnen', close: 'Menü schließen', skip: 'Zum Inhalt springen', language: 'Sprache' },
  fr: { features: 'Fonctions', docs: 'Documentation', roadmap: 'Feuille de route', blog: 'Blog', about: 'À propos', support: 'Soutenir', download: 'Télécharger', menu: 'Menu', open: 'Ouvrir le menu', close: 'Fermer le menu', skip: 'Aller au contenu', language: 'Langue' },
  it: { features: 'Funzioni', docs: 'Documentazione', roadmap: 'Roadmap', blog: 'Blog', about: 'Informazioni', support: 'Sostieni', download: 'Scarica', menu: 'Menu', open: 'Apri menu', close: 'Chiudi menu', skip: 'Vai al contenuto', language: 'Lingua' },
} satisfies Record<Locale, Record<string, string>>;

export const landing = {
  es: { title: 'Mouzi — organiza automáticamente tu carpeta de Descargas', description: 'Organizador gratuito y de código abierto para Windows y Linux. Ordena archivos con reglas locales, sin cuentas ni telemetría.', eyebrow: 'GRATIS · CÓDIGO ABIERTO · SOLO LOCAL', hero: 'Tu carpeta de Descargas, ordenada antes de convertirse en un problema.', lead: 'Mouzi organiza silenciosamente los archivos nuevos mediante reglas que tú controlas. Sin nube, sin cuentas y sin telemetría.', github: 'Ver en GitHub', kicker: 'QUÉ HACE', section: 'Una aplicación pequeña con un comportamiento preciso.', sectionLead: 'Mouzi permanece en la bandeja del sistema y solo actúa cuando una carpeta vigilada necesita atención.', automatic: 'Organización automática', automaticBody: 'Vigila las carpetas que elijas y mueve cada archivo nuevo al lugar correcto según tus reglas.', rules: 'Reglas personalizadas', rulesBody: 'Clasifica por extensión, nombre o expresión regular y usa carpetas dinámicas por fecha.', undo: 'Historial y deshacer', undoBody: 'Cada movimiento se guarda localmente. Si algo acaba en un lugar inesperado, puedes deshacerlo con un clic.', privacy: 'Privacidad desde el diseño', privacyBody: 'Tus archivos, nombres y reglas nunca salen de tu ordenador.', local: 'Procesamiento local', account: 'Sin cuentas', telemetry: 'Sin telemetría', cta: 'Descargar Mouzi', faq: 'Preguntas frecuentes' },
  pl: { title: 'Mouzi — automatyczne porządkowanie folderu Pobrane', description: 'Darmowy organizer plików dla Windows i Linux. Lokalne reguły, bez konta i telemetrii.', eyebrow: 'ZA DARMO · OPEN SOURCE · TYLKO LOKALNIE', hero: 'Twój folder Pobrane, uporządkowany zanim stanie się problemem.', lead: 'Mouzi po cichu porządkuje nowe pliki według reguł, które kontrolujesz. Bez chmury, kont i telemetrii.', github: 'Zobacz na GitHubie', kicker: 'CO POTRAFI', section: 'Mała aplikacja, konkretne działanie.', sectionLead: 'Mouzi działa w zasobniku systemowym i reaguje tylko wtedy, gdy obserwowany folder wymaga uwagi.', automatic: 'Automatyczne porządkowanie', automaticBody: 'Obserwuje wybrane foldery i przenosi nowe pliki zgodnie z Twoimi regułami.', rules: 'Własne reguły', rulesBody: 'Sortuj według rozszerzenia, nazwy lub wyrażenia regularnego oraz używaj folderów zależnych od daty.', undo: 'Historia i cofanie', undoBody: 'Każde przeniesienie jest zapisywane lokalnie i można je cofnąć jednym kliknięciem.', privacy: 'Prywatność od podstaw', privacyBody: 'Pliki, nazwy i reguły nigdy nie opuszczają Twojego komputera.', local: 'Lokalne przetwarzanie', account: 'Bez kont', telemetry: 'Bez telemetrii', cta: 'Pobierz Mouzi', faq: 'Częste pytania' },
  de: { title: 'Mouzi — den Downloads-Ordner automatisch organisieren', description: 'Kostenloser Open-Source-Dateiorganisator für Windows und Linux. Lokal, ohne Konto und Telemetrie.', eyebrow: 'KOSTENLOS · OPEN SOURCE · NUR LOKAL', hero: 'Dein Downloads-Ordner, sortiert bevor er zum Problem wird.', lead: 'Mouzi organisiert neue Dateien unauffällig nach deinen Regeln. Keine Cloud, keine Konten, keine Telemetrie.', github: 'Auf GitHub ansehen', kicker: 'FUNKTIONEN', section: 'Kleine App, präzises Verhalten.', sectionLead: 'Mouzi bleibt im Infobereich und wird nur aktiv, wenn ein überwachter Ordner Aufmerksamkeit braucht.', automatic: 'Automatische Organisation', automaticBody: 'Überwacht ausgewählte Ordner und verschiebt neue Dateien nach deinen Regeln.', rules: 'Eigene Regeln', rulesBody: 'Sortiere nach Erweiterung, Name oder regulärem Ausdruck und nutze dynamische Datumsordner.', undo: 'Verlauf und Rückgängig', undoBody: 'Jede Verschiebung wird lokal gespeichert und lässt sich mit einem Klick rückgängig machen.', privacy: 'Datenschutz als Grundlage', privacyBody: 'Dateien, Namen und Regeln verlassen deinen Computer nie.', local: 'Lokale Verarbeitung', account: 'Keine Konten', telemetry: 'Keine Telemetrie', cta: 'Mouzi herunterladen', faq: 'Häufige Fragen' },
  fr: { title: 'Mouzi — organiser automatiquement le dossier Téléchargements', description: 'Organisateur de fichiers gratuit et open source pour Windows et Linux. Local, sans compte ni télémétrie.', eyebrow: 'GRATUIT · OPEN SOURCE · EN LOCAL', hero: 'Votre dossier Téléchargements, rangé avant de devenir un problème.', lead: 'Mouzi organise discrètement les nouveaux fichiers selon vos règles. Sans cloud, sans compte et sans télémétrie.', github: 'Voir sur GitHub', kicker: 'FONCTIONS', section: 'Une petite application au comportement précis.', sectionLead: 'Mouzi reste dans la zone de notification et intervient seulement lorsqu’un dossier surveillé en a besoin.', automatic: 'Organisation automatique', automaticBody: 'Surveille les dossiers choisis et déplace chaque nouveau fichier selon vos règles.', rules: 'Règles personnalisées', rulesBody: 'Triez par extension, nom ou expression régulière et créez des dossiers dynamiques par date.', undo: 'Historique et annulation', undoBody: 'Chaque déplacement est enregistré localement et peut être annulé en un clic.', privacy: 'Confidentialité dès la conception', privacyBody: 'Vos fichiers, leurs noms et vos règles ne quittent jamais votre ordinateur.', local: 'Traitement local', account: 'Sans compte', telemetry: 'Sans télémétrie', cta: 'Télécharger Mouzi', faq: 'Questions fréquentes' },
  it: { title: 'Mouzi — organizza automaticamente la cartella Download', description: 'Organizzatore di file gratuito e open source per Windows e Linux. Locale, senza account né telemetria.', eyebrow: 'GRATUITO · OPEN SOURCE · SOLO LOCALE', hero: 'La cartella Download, ordinata prima che diventi un problema.', lead: 'Mouzi organizza in silenzio i nuovi file usando le regole che controlli tu. Niente cloud, account o telemetria.', github: 'Vedi su GitHub', kicker: 'FUNZIONI', section: 'Una piccola app dal comportamento preciso.', sectionLead: 'Mouzi resta nell’area di notifica e interviene solo quando una cartella monitorata richiede attenzione.', automatic: 'Organizzazione automatica', automaticBody: 'Controlla le cartelle scelte e sposta ogni nuovo file secondo le tue regole.', rules: 'Regole personalizzate', rulesBody: 'Ordina per estensione, nome o espressione regolare e crea cartelle dinamiche per data.', undo: 'Cronologia e annullamento', undoBody: 'Ogni spostamento viene salvato localmente e può essere annullato con un clic.', privacy: 'Privacy fin dalla progettazione', privacyBody: 'File, nomi e regole non lasciano mai il tuo computer.', local: 'Elaborazione locale', account: 'Nessun account', telemetry: 'Nessuna telemetria', cta: 'Scarica Mouzi', faq: 'Domande frequenti' },
} as const;

export const homeSections = {
  es: { demoK:'MOUZI EN ACCIÓN',demoT:'Del caos al orden, sin interrumpirte.',demoL:'Ejecuta unas reglas normales y observa cómo cada archivo encuentra su lugar. Todo ocurre localmente.',privacyK:'PRIVACIDAD',privacyT:'Tus archivos nunca salen de tu ordenador.',privacyL:'Mouzi no tiene servidor. No hay nada que registrar, sincronizar ni filtrar.',privacyItems:['Sin procesamiento en la nube','Sin cuenta','Sin telemetría','No se transmiten nombres de archivo','Reglas e historial guardados localmente','Código abierto para inspeccionarlo'],rulesK:'REGLAS',rulesT:'Una condición, un destino. Así de sencillo.',rulesL:'Prueba reglas reales y comprueba cómo Mouzi determina cada carpeta de destino.',docsK:'DOCUMENTACIÓN',docsT:'Configúralo a tu manera.',docsL:'Las guías técnicas completas siguen disponibles en inglés mientras ampliamos las traducciones.',securityK:'SEGURIDAD',securityT:'Versiones públicas y verificables.',securityL:'Los artefactos se generan en GitHub Actions desde commits etiquetados. El código y el proceso de compilación son públicos.',downloadK:'DESCARGAR',downloadT:'Gratis para siempre.',downloadL:'Elige Windows o Linux. Las dos versiones incluyen las mismas funciones.',roadmapK:'PRÓXIMAMENTE',roadmapT:'Mouzi sigue mejorando.',roadmapL:'Las próximas versiones mejorarán las reglas, la accesibilidad y el control sobre tus carpetas.',communityK:'CÓDIGO ABIERTO',communityT:'Construido en público.',communityL:'Informa de errores, propone funciones, mejora una traducción o revisa el código.',fundingK:'APOYO',fundingT:'Ayuda a mantener Mouzi independiente.',fundingL:'Mouzi es gratuito. Tu apoyo ayuda con la infraestructura, las pruebas y la firma de código.',finalT:'¿Listo para recuperar tu carpeta de Descargas?',readDocs:'Abrir documentación',roadmap:'Ver hoja de ruta',contribute:'Contribuir en GitHub',sponsor:'Apoyar Mouzi'},
  pl: { demoK:'ZOBACZ W DZIAŁANIU',demoT:'Od chaosu do porządku, bez przeszkadzania.',demoL:'Uruchom zwykłe reguły i zobacz, jak każdy plik trafia na swoje miejsce. Wszystko odbywa się lokalnie.',privacyK:'PRYWATNOŚĆ',privacyT:'Twoje pliki nigdy nie opuszczają komputera.',privacyL:'Mouzi nie ma serwera. Nie musisz się rejestrować ani niczego synchronizować.',privacyItems:['Bez przetwarzania w chmurze','Bez konta','Bez telemetrii','Nazwy plików nie są wysyłane','Reguły i historia zapisane lokalnie','Kod dostępny do weryfikacji'],rulesK:'REGUŁY',rulesT:'Jeden warunek, jedno miejsce docelowe.',rulesL:'Wypróbuj prawdziwe reguły i zobacz, jak Mouzi wybiera folder docelowy.',docsK:'DOKUMENTACJA',docsT:'Skonfiguruj Mouzi po swojemu.',docsL:'Pełne przewodniki techniczne są obecnie po angielsku. Kolejne tłumaczenia dodamy później.',securityK:'BEZPIECZEŃSTWO',securityT:'Publiczne i możliwe do zweryfikowania wydania.',securityL:'Pliki są budowane w GitHub Actions z oznaczonych commitów, a kod i proces budowania są publiczne.',downloadK:'POBIERANIE',downloadT:'Za darmo, na zawsze.',downloadL:'Wybierz Windows lub Linux. Obie wersje mają te same funkcje.',roadmapK:'CO DALEJ',roadmapT:'Mouzi nadal się rozwija.',roadmapL:'Następne wydania rozwiną reguły, dostępność i kontrolę nad folderami.',communityK:'OPEN SOURCE',communityT:'Tworzone publicznie.',communityL:'Zgłoś błąd, zaproponuj funkcję, popraw tłumaczenie lub przejrzyj kod.',fundingK:'WSPARCIE',fundingT:'Pomóż zachować niezależność Mouzi.',fundingL:'Mouzi jest darmowe. Wsparcie pomaga finansować infrastrukturę, testy i podpisywanie kodu.',finalT:'Gotowy odzyskać kontrolę nad folderem Pobrane?',readDocs:'Otwórz dokumentację',roadmap:'Zobacz plan rozwoju',contribute:'Współtwórz na GitHubie',sponsor:'Wesprzyj Mouzi'},
  de: { demoK:'MOUZI IN AKTION',demoT:'Vom Chaos zur Ordnung, ganz nebenbei.',demoL:'Führe alltägliche Regeln aus und sieh zu, wie jede Datei ihren Platz findet. Alles bleibt lokal.',privacyK:'DATENSCHUTZ',privacyT:'Deine Dateien verlassen deinen Computer nie.',privacyL:'Mouzi hat keinen Server. Keine Anmeldung, keine Synchronisierung und keine Datenübertragung.',privacyItems:['Keine Cloud-Verarbeitung','Kein Konto','Keine Telemetrie','Keine Dateinamen übertragen','Regeln und Verlauf lokal gespeichert','Offener Quellcode'],rulesK:'REGELN',rulesT:'Eine Bedingung, ein Ziel. Das ist eine Regel.',rulesL:'Probiere echte Regeln aus und sieh, wie Mouzi den Zielordner bestimmt.',docsK:'DOKUMENTATION',docsT:'Richte Mouzi nach deinen Wünschen ein.',docsL:'Die vollständigen technischen Anleitungen sind vorerst auf Englisch verfügbar.',securityK:'SICHERHEIT',securityT:'Öffentlich nachvollziehbare Releases.',securityL:'Artefakte werden in GitHub Actions aus markierten Commits erstellt. Quellcode und Build-Prozess sind öffentlich.',downloadK:'DOWNLOAD',downloadT:'Dauerhaft kostenlos.',downloadL:'Wähle Windows oder Linux. Beide Versionen bieten dieselben Funktionen.',roadmapK:'AUSBLICK',roadmapT:'Mouzi entwickelt sich weiter.',roadmapL:'Kommende Versionen verbessern Regeln, Barrierefreiheit und Ordnerkontrolle.',communityK:'OPEN SOURCE',communityT:'Öffentlich entwickelt.',communityL:'Melde Fehler, schlage Funktionen vor, verbessere Übersetzungen oder prüfe den Code.',fundingK:'UNTERSTÜTZUNG',fundingT:'Hilf Mouzi unabhängig zu bleiben.',fundingL:'Mouzi ist kostenlos. Unterstützung finanziert Infrastruktur, Tests und Codesignierung.',finalT:'Bereit, deinen Downloads-Ordner zurückzugewinnen?',readDocs:'Dokumentation öffnen',roadmap:'Roadmap ansehen',contribute:'Auf GitHub beitragen',sponsor:'Mouzi unterstützen'},
  fr: { demoK:'MOUZI EN ACTION',demoT:'Du chaos à l’ordre, en toute discrétion.',demoL:'Lancez quelques règles courantes et regardez chaque fichier trouver sa place. Tout reste local.',privacyK:'CONFIDENTIALITÉ',privacyT:'Vos fichiers ne quittent jamais votre ordinateur.',privacyL:'Mouzi n’a aucun serveur. Rien à créer, synchroniser ou transmettre.',privacyItems:['Aucun traitement cloud','Aucun compte','Aucune télémétrie','Aucun nom de fichier transmis','Règles et historique stockés localement','Code source vérifiable'],rulesK:'RÈGLES',rulesT:'Une condition, une destination. Voilà une règle.',rulesL:'Essayez de vraies règles et voyez comment Mouzi choisit chaque destination.',docsK:'DOCUMENTATION',docsT:'Configurez Mouzi à votre façon.',docsL:'Les guides techniques complets restent disponibles en anglais pour le moment.',securityK:'SÉCURITÉ',securityT:'Des versions publiques et vérifiables.',securityL:'Les fichiers sont construits dans GitHub Actions à partir de commits balisés. Le code et la compilation sont publics.',downloadK:'TÉLÉCHARGEMENT',downloadT:'Gratuit pour toujours.',downloadL:'Choisissez Windows ou Linux. Les deux versions proposent les mêmes fonctions.',roadmapK:'À VENIR',roadmapT:'Mouzi continue de progresser.',roadmapL:'Les prochaines versions amélioreront les règles, l’accessibilité et le contrôle des dossiers.',communityK:'OPEN SOURCE',communityT:'Développé publiquement.',communityL:'Signalez un bug, proposez une fonction, améliorez une traduction ou examinez le code.',fundingK:'SOUTIEN',fundingT:'Aidez Mouzi à rester indépendant.',fundingL:'Mouzi est gratuit. Votre soutien finance l’infrastructure, les tests et la signature du code.',finalT:'Prêt à reprendre le contrôle de vos téléchargements ?',readDocs:'Ouvrir la documentation',roadmap:'Voir la feuille de route',contribute:'Contribuer sur GitHub',sponsor:'Soutenir Mouzi'},
  it: { demoK:'MOUZI IN AZIONE',demoT:'Dal caos all’ordine, senza disturbarti.',demoL:'Esegui alcune regole comuni e guarda ogni file trovare il suo posto. Tutto avviene in locale.',privacyK:'PRIVACY',privacyT:'I tuoi file non lasciano mai il computer.',privacyL:'Mouzi non ha server. Nessuna registrazione, sincronizzazione o trasmissione.',privacyItems:['Nessuna elaborazione cloud','Nessun account','Nessuna telemetria','Nessun nome file trasmesso','Regole e cronologia salvate in locale','Codice sorgente verificabile'],rulesK:'REGOLE',rulesT:'Una condizione, una destinazione. Questa è una regola.',rulesL:'Prova regole reali e osserva come Mouzi determina ogni destinazione.',docsK:'DOCUMENTAZIONE',docsT:'Configura Mouzi come preferisci.',docsL:'Le guide tecniche complete restano disponibili in inglese per il momento.',securityK:'SICUREZZA',securityT:'Versioni pubbliche e verificabili.',securityL:'I file vengono creati in GitHub Actions da commit con tag. Codice e processo di build sono pubblici.',downloadK:'DOWNLOAD',downloadT:'Gratis per sempre.',downloadL:'Scegli Windows o Linux. Entrambe le versioni offrono le stesse funzioni.',roadmapK:'IN ARRIVO',roadmapT:'Mouzi continua a migliorare.',roadmapL:'Le prossime versioni miglioreranno regole, accessibilità e controllo delle cartelle.',communityK:'OPEN SOURCE',communityT:'Sviluppato pubblicamente.',communityL:'Segnala bug, proponi funzioni, migliora una traduzione o controlla il codice.',fundingK:'SUPPORTO',fundingT:'Aiuta Mouzi a restare indipendente.',fundingL:'Mouzi è gratuito. Il supporto finanzia infrastruttura, test e firma del codice.',finalT:'Pronto a riprenderti la cartella Download?',readDocs:'Apri la documentazione',roadmap:'Vedi la roadmap',contribute:'Contribuisci su GitHub',sponsor:'Sostieni Mouzi'},
} as const;
